# Topics to record (used by bag.py)
RAW:      # these topics will NOT have the robot name prepended as a namespace (i.e. absolute paths)
  - /clock
  - /diagnostics
  - /diagnostics_agg
  - /diagnostics_toplevel_state
  - /tf
  - /tf_aggregate
  - /tf_static
  - /rviz/team_behavior_graph/update
ROBOT_NAME:  # these topics WILL have the robot name prepended ("blah" -> "chinook/blah")
  - frame_notifications
  - accepted_frame_notifications
  - cmd_vel
  - cmd_drive
  - feedback
  - microstrain/data
  - microstrain/data_ned
  - microstrain/data_enu
  - microstrain/data_ned/orientation
  - joint_states
  - twist_marker_server/cmd_vel
  - status
  - jackal_velocity_controller/cmd_vel
  - jackal_velocity_controller/odom
  - lidar_points
  - navigation_manager/status
  - master_discovery/changes
  - master_discovery/linkstats
  - odom
  - odometry/filtered
  - pose
  - raw_odom
  - point_cloud_cache/renderers/full_map_compressed
  - local/joy
  - local/cmd_vel
  - jackal_velocity_controller/cmd_vel_out
  - forward/color/camera_info
  - forward/color/image_raw/compressed
#  - forward/aligned_depth_to_color/camera_info
#  - forward/aligned_depth_to_color/image_raw/compressedDepth
  - forward/infra1/camera_info
  - forward/infra1/image_rect_raw/compressed
#  - forward/infra2/camera_info
#  - forward/infra2/image_rect_raw/compressed
  - forward/imu_info
  - forward/imu
  - forward/extrinsics/depth_to_color
  - detection_out_topic
  - worldmodel_rviz/object_markers
  - detected_objects
  - detector_manager_node/object_visualization
  - omnigraph/visuals
  - global_costmap/costmap/costmap
  - orcvio/active_feature_point_cloud
  - orcvio/msckf_feature_point_cloud
  - orcvio/odom
  - orcvio/path
  - orcvio/poseout
  - orcvio/stable_feature_point_cloud
  - orcvio/visualization_image/compressed
  - orcvio/visualization_markers
